### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by IanaKhitsko** [dionissqq/euro_diffusion#5]
https://github.com/dionissqq/euro_diffusion/blob/4de82cf19d36f65c54b05faf56466345bdbc434a/main.py#L125

first by completion day, then by name

**Comment by dionissqq** [comment]
Instead of sorting of by completion date and then look for same values we can just sort by name first and then by completion. This is achieved by specific of algorithm timsort that is default in python and does not change the presorted orders if values are the same. 

For more specifics check the Timsort algorithm
